# API-first development with OpenAPI
# 由 openapi-generator 於編譯時產生 Spring MVC stubs；paths 不含 /api 前綴
openapi: '3.0.1'
info:
  title: 'turnbridgeBackend'
  version: 1.0.0
  description: |
    TurnBridge（橋票雲）Inbound/Outbound API
    - 支援 CSV/ZIP 上傳（多 Profile 自動判斷或手動指定）
    - 批次狀態/明細查詢、回饋 CSV 下載
    - 後端會將資料轉 Canonical，產生 MIG 4.1 XML 並投遞至 Turnkey 目錄
servers:
  # 注意：這裡的 URL 已含 /api，所以 paths 不要再加 /api
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile

tags:
  - name: Upload
    description: 上傳與批次建立
  - name: Jobs
    description: 批次與明細查詢
  - name: Results
    description: 回饋生成與下載

paths:
  # ========= 上傳入口 =========
  /invoices/upload:
    post:
      operationId: uploadInvoices
      tags: [Upload]
      summary: 上傳發票 CSV 或 ZIP
      description: |
        用途：
        - 接收 CSV/ZIP，建立 UploadJob 與 JobItem（非同步處理）
        - 若未指定 profile，系統會依抬頭欄位自動判斷（Legacy / Canonical）
        - 建議檔名：INV_UPLOAD_{sellerId}_{yyyyMMddHHmmss}.csv|zip

        容量：
        - >50MB 請改分批或透過 SFTP（由 Agent 監看）
      security: [ { jwt: [] } ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file, sellerId]
              properties:
                file:
                  type: string
                  format: binary
                  description: 上傳檔案（CSV 或 ZIP，UTF-8）
                sellerId:
                  type: string
                  description: 賣方統編或客戶識別碼
                  example: "24567891"
                profile:
                  type: string
                  description: 選填；若省略則由系統自動偵測
                  enum: [Profile-Legacy, Profile-Canonical]
                  example: "Profile-Canonical"
      responses:
        '202':
          description: 已接收並建立批次（非同步）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadAck'
              examples:
                accepted:
                  summary: 建立成功的回覆
                  value:
                    jobId: "JOB-20251105-0001"
                    receivedAt: "2025-11-05T04:12:33Z"
                    profile: "Profile-Legacy"
                    itemsCount: 1200
        '400': { $ref: '#/components/responses/Problem' }
        '401': { $ref: '#/components/responses/Problem' }
        '413':
          description: 檔案過大（請使用分批或 SFTP）

  # ========= 批次狀態 =========
  /upload-jobs/{jobId}:
    get:
      operationId: getUploadJob
      tags: [Jobs]
      summary: 查詢上傳批次狀態
      description: 回傳 UploadJob 當前狀態與統計
      security: [ { jwt: [] } ]
      parameters:
        - name: jobId
          in: path
          required: true
          description: 批次識別碼（由上傳時回傳）
          schema: { type: string }
          example: "JOB-20251105-0001"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UploadJob' }
              examples:
                processing:
                  summary: 處理中批次
                  value:
                    jobId: "JOB-20251105-0001"
                    sellerId: "24567891"
                    profile: "Profile-Legacy"
                    status: "VALIDATING"
                    createdAt: "2025-11-05T04:12:33Z"
                    updatedAt: "2025-11-05T04:16:01Z"
                    counters: { total: 1200, accepted: 1180, failed: 20, sent: 0 }
        '401': { $ref: '#/components/responses/Problem' }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 批次統計 =========
  /upload-jobs/{jobId}/stats:
    get:
      operationId: getUploadJobStats
      tags: [Jobs]
      summary: 取得批次統計
      security: [ { jwt: [] } ]
      parameters:
        - in: path
          name: jobId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UploadJobStats' }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 批次明細 =========
  /upload-jobs/{jobId}/items:
    get:
      operationId: listUploadJobItems
      tags: [Jobs]
      summary: 查詢批次明細與每筆處理結果
      description: |
        **JHipster 風格分頁**：回傳 body 為「陣列」，分頁資訊在 headers。
        - `X-Total-Count`: 總筆數
        - `Link`: RFC5988 分頁連結（first, prev, next, last）
      security: [ { jwt: [] } ]
      parameters:
        - name: jobId
          in: path
          required: true
          description: 批次識別碼
          schema: { type: string }
          example: "JOB-20251105-0001"
        - name: page
          in: query
          description: 第幾頁（0-based）
          schema: { type: integer, minimum: 0, default: 0 }
        - name: size
          in: query
          description: 每頁筆數
          schema: { type: integer, minimum: 1, maximum: 500, default: 100 }
        - name: status
          in: query
          description: 以處理狀態過濾
          schema: { type: string, enum: [QUEUED, OK, ERROR] }
          example: "ERROR"
        - name: resultCode
          in: query
          description: 以錯誤碼過濾（例如 0402、0510）
          schema: { type: string }
          example: "0510"
      responses:
        '200':
          description: OK（body 為陣列；分頁 headers 見上）
          headers:
            X-Total-Count:
              description: 總筆數
              schema: { type: integer }
            Link:
              description: 分頁導覽連結（first, prev, next, last）
              schema: { type: string }
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/JobItemResult' }
        '401': { $ref: '#/components/responses/Problem' }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 原始檔下載 =========
  /upload-jobs/{jobId}/original:
    get:
      operationId: downloadOriginal
      tags: [Jobs]
      summary: 下載原始上傳檔
      security: [ { jwt: [] } ]
      parameters:
        - in: path
          name: jobId
          required: true
          schema: { type: string }
        - in: query
          name: bom
          schema: { type: boolean, default: true }
          description: 文字檔是否加入 UTF-8 BOM
      responses:
        '200':
          description: 原始檔內容
          content:
            '*/*':
              schema: { type: string, format: binary }
          headers:
            Content-Disposition:
              description: 下載檔名
              schema: { type: string }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 回饋 CSV 下載 =========
  /upload-jobs/{jobId}/result:
    get:
      operationId: downloadUploadJobResult
      tags: [Results]
      summary: 下載回饋 CSV（原欄位 + result_* 欄位）
      description: |
        下載內容：
        - 以原上傳 CSV 的欄位為基礎，尾欄加上：
          result_code, result_msg, trace_id, assigned_invoice_no
        - 預設輸出 UTF-8 with BOM（Excel 友善）
      security: [ { jwt: [] } ]
      parameters:
        - name: jobId
          in: path
          required: true
          description: 批次識別碼
          schema: { type: string }
          example: "JOB-20251105-0001"
        - name: bom
          in: query
          description: 是否加入 UTF-8 BOM（預設 true）
          schema: { type: boolean, default: true }
      responses:
        '200':
          description: CSV 檔案內容
          content:
            text/csv:
              schema: { type: string, format: binary }
          headers:
            Content-Disposition:
              description: 下載檔名
              schema: { type: string }
              example: attachment; filename="JOB-20251105-0001-result.csv"
        '401': { $ref: '#/components/responses/Problem' }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 重試失敗明細 =========
  /upload-jobs/{jobId}/retry-failed:
    post:
      operationId: retryFailedItems
      tags: [Jobs]
      summary: 將 ERROR 明細重試（改為 QUEUED 並清空錯誤欄位）
      security: [ { jwt: [] } ]
      parameters:
        - in: path
          name: jobId
          required: true
          schema: { type: string }
      responses:
        '202': { description: 已接受 }
        '404': { $ref: '#/components/responses/Problem' }

  # ========= 以 ID 下載任何儲存物件 =========
  /stored-objects/{id}/download:
    get:
      operationId: downloadStoredObject
      tags: [Results]
      summary: 以 id 下載儲存物件
      security: [ { jwt: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer, format: int64 }
        - in: query
          name: bom
          schema: { type: boolean, default: false }
      responses:
        '200':
          description: 檔案內容
          content:
            '*/*':
              schema: { type: string, format: binary }
          headers:
            Content-Disposition:
              description: 下載檔名
              schema: { type: string }
        '404': { $ref: '#/components/responses/Problem' }

components:
  # ====== 保留 JHipster 預設的 Problem 響應 ======
  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri
                default: 'about:blank'
                example: 'https://www.jhipster.tech/problem/problem-with-message'
              title:
                type: string
                example: 'Bad Request'
              status:
                type: integer
                format: int32
                example: 400
              detail:
                type: string
                example: 'CSV 欄位 buyerName 缺漏'
              instance:
                type: string
                format: uri

  # ====== SecuritySchemes（jwt/basic） ======
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
    basic:
      type: http
      description: Basic Authentication
      scheme: basic

  # ====== DTO Schemas ======
  schemas:
    UploadAck:
      type: object
      description: 上傳成功建立批次後的回覆（非同步處理）
      properties:
        jobId:
          type: string
          description: 批次識別碼
          example: "JOB-20251105-0001"
        receivedAt:
          type: string
          format: date-time
          description: 伺服器接收時間（UTC ISO-8601）
          example: "2025-11-05T04:12:33Z"
        profile:
          type: string
          description: 使用的 Profile 名稱（若為自動偵測，回傳判定結果）
          example: "Profile-Legacy"
        itemsCount:
          type: integer
          description: 解析得到的列數（ZIP 需解開後才精準）
          example: 1200

    UploadJob:
      type: object
      description: 上傳批次主檔狀態與統計
      properties:
        jobId:     { type: string, example: "JOB-20251105-0001" }
        sellerId:  { type: string, example: "24567891" }
        profile:   { type: string, example: "Profile-Legacy" }
        status:
          type: string
          description: 批次處理狀態
          enum: [RECEIVED, PARSING, VALIDATING, PACKING, SENT, RESULT_READY, FAILED]
          example: "VALIDATING"
        createdAt: { type: string, format: date-time, example: "2025-11-05T04:12:33Z" }
        updatedAt: { type: string, format: date-time, example: "2025-11-05T04:16:01Z" }
        counters:
          type: object
          description: 批次統計數量
          properties:
            total:    { type: integer, example: 1200 }
            accepted: { type: integer, example: 1180 }
            failed:   { type: integer, example: 20 }
            sent:     { type: integer, example: 0 }

    UploadJobStats:
      type: object
      description: 成功/失敗/待處理統計
      properties:
        total:  { type: integer, example: 1200 }
        ok:     { type: integer, example: 1180 }
        error:  { type: integer, example: 20 }
        queued: { type: integer, example: 0 }

    JobItemResult:
      type: object
      description: 批次中每筆資料的處理結果（含錯誤碼與訊息）
      properties:
        lineNo:
          type: integer
          description: 原始檔行號（從 1 起算）
          example: 12
        traceId:
          type: string
          description: 該筆資料的全流程追蹤 ID
          example: "TRC-20251105-0001-000012"
        invoiceNo:
          type: string
          nullable: true
          description: 系統分配或上傳指定的發票號碼（若尚未分配可為 null）
          example: "AB12345678"
        buyerId:
          type: string
          example: "12233456"
        amount:
          type: number
          format: double
          example: 1580
        status:
          type: string
          enum: [QUEUED, OK, ERROR]
          example: "ERROR"
        resultCode:
          type: string
          description: 錯誤碼（如 0402 欄位缺漏、0510 金額不平…）
          example: "0510"
        resultMsg:
          type: string
          description: 錯誤訊息（可讀）
          example: "含稅/未稅金額不平"

# 全域 Security（可由 Filter/Config 覆蓋）
security:
  - jwt: []
  - basic: []
