#!/usr/bin/env python3
"""Simple Turnkey mock processor for DEV/UAT.

Monitors an INBOX directory, generates ACK/ERROR XML files in OUTBOX,
and moves processed files into INBOX/_processed.

Usage:
  python docs/integration/scripts/mock-turnkey.py \
    --inbox /turnkey/INBOX --outbox /turnkey/OUTBOX

Optional flags:
  --interval 30        # polling interval seconds
  --error-pattern FAIL # filenames containing pattern go to ERROR
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Iterable


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Mock Turnkey processor")
    parser.add_argument("--inbox", required=True, help="Path to INBOX directory")
    parser.add_argument("--outbox", required=True, help="Path to OUTBOX directory")
    parser.add_argument("--error-dir", default=None, help="Optional ERROR directory")
    parser.add_argument("--interval", type=int, default=60, help="Polling interval seconds")
    parser.add_argument(
        "--error-pattern",
        default=".error",
        help="If filename contains this pattern, emit ERROR instead of ACK",
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Process current files once and exit (no loop)",
    )
    return parser.parse_args()


def ensure_dirs(*paths: Path) -> None:
    for path in paths:
        if path is None:
            continue
        path.mkdir(parents=True, exist_ok=True)


def iter_xml(inbox: Path) -> Iterable[Path]:
    for path in sorted(inbox.glob("*.xml")):
        if path.is_file():
            yield path


def write_ack(outbox: Path, base: str, ok: bool) -> None:
    ts = dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    if ok:
        content = (
            f"<ACK messageId=\"{base}\" timestamp=\"{ts}\">\n"
            f"  <Status>ACKED</Status>\n"
            f"</ACK>\n"
        )
        suffix = ".ack.xml"
    else:
        content = (
            f"<ERROR messageId=\"{base}\" timestamp=\"{ts}\">\n"
            f"  <Code>TKY-9999</Code>\n"
            f"  <Message>Mock error generated by Turnkey simulator</Message>\n"
            f"</ERROR>\n"
        )
        suffix = ".error.xml"
    outbox.mkdir(parents=True, exist_ok=True)
    dest = outbox / f"{base}{suffix}"
    dest.write_text(content, encoding="utf-8")
    print(f"[mock-turnkey] Wrote {dest}")


def main() -> int:
    args = parse_args()
    inbox = Path(args.inbox)
    outbox = Path(args.outbox)
    error_dir = Path(args.error_dir) if args.error_dir else None

    ensure_dirs(inbox, outbox, error_dir)
    processed_dir = inbox / "_processed"
    processed_dir.mkdir(exist_ok=True)

    def process_once() -> None:
        for xml_path in iter_xml(inbox):
            base = xml_path.stem
            is_error = args.error_pattern and args.error_pattern in xml_path.name
            write_ack(error_dir if is_error and error_dir else outbox, base, not is_error)
            target = processed_dir / xml_path.name
            shutil.move(str(xml_path), target)
            print(f"[mock-turnkey] Moved {xml_path} -> {target}")

    if args.once:
        process_once()
        return 0

    try:
        while True:
            process_once()
            time.sleep(args.interval)
    except KeyboardInterrupt:
        print("[mock-turnkey] Stopped.")
        return 0


+if __name__ == "__main__":
+    sys.exit(main())
*** End Patch
