package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportFileItemErrorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemErrorAllPropertiesEquals(ImportFileItemError expected, ImportFileItemError actual) {
        assertImportFileItemErrorAutoGeneratedPropertiesEquals(expected, actual);
        assertImportFileItemErrorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemErrorAllUpdatablePropertiesEquals(ImportFileItemError expected, ImportFileItemError actual) {
        assertImportFileItemErrorUpdatableFieldsEquals(expected, actual);
        assertImportFileItemErrorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemErrorAutoGeneratedPropertiesEquals(ImportFileItemError expected, ImportFileItemError actual) {
        assertThat(actual)
            .as("Verify ImportFileItemError auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemErrorUpdatableFieldsEquals(ImportFileItemError expected, ImportFileItemError actual) {
        assertThat(actual)
            .as("Verify ImportFileItemError relevant properties")
            .satisfies(a -> assertThat(a.getColumnIndex()).as("check columnIndex").isEqualTo(expected.getColumnIndex()))
            .satisfies(a -> assertThat(a.getFieldName()).as("check fieldName").isEqualTo(expected.getFieldName()))
            .satisfies(a -> assertThat(a.getErrorCode()).as("check errorCode").isEqualTo(expected.getErrorCode()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getOccurredAt()).as("check occurredAt").isEqualTo(expected.getOccurredAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemErrorUpdatableRelationshipsEquals(ImportFileItemError expected, ImportFileItemError actual) {
        assertThat(actual)
            .as("Verify ImportFileItemError relationships")
            .satisfies(a -> assertThat(a.getImportFileItem()).as("check importFileItem").isEqualTo(expected.getImportFileItem()));
    }
}
