package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportFileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileAllPropertiesEquals(ImportFile expected, ImportFile actual) {
        assertImportFileAutoGeneratedPropertiesEquals(expected, actual);
        assertImportFileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileAllUpdatablePropertiesEquals(ImportFile expected, ImportFile actual) {
        assertImportFileUpdatableFieldsEquals(expected, actual);
        assertImportFileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileAutoGeneratedPropertiesEquals(ImportFile expected, ImportFile actual) {
        assertThat(actual)
            .as("Verify ImportFile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileUpdatableFieldsEquals(ImportFile expected, ImportFile actual) {
        assertThat(actual)
            .as("Verify ImportFile relevant properties")
            .satisfies(a -> assertThat(a.getImportType()).as("check importType").isEqualTo(expected.getImportType()))
            .satisfies(a -> assertThat(a.getOriginalFilename()).as("check originalFilename").isEqualTo(expected.getOriginalFilename()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.getTotalCount()).as("check totalCount").isEqualTo(expected.getTotalCount()))
            .satisfies(a -> assertThat(a.getSuccessCount()).as("check successCount").isEqualTo(expected.getSuccessCount()))
            .satisfies(a -> assertThat(a.getErrorCount()).as("check errorCount").isEqualTo(expected.getErrorCount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getLegacyType()).as("check legacyType").isEqualTo(expected.getLegacyType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileUpdatableRelationshipsEquals(ImportFile expected, ImportFile actual) {
        assertThat(actual)
            .as("Verify ImportFile relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
