package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportFileLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileLogAllPropertiesEquals(ImportFileLog expected, ImportFileLog actual) {
        assertImportFileLogAutoGeneratedPropertiesEquals(expected, actual);
        assertImportFileLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileLogAllUpdatablePropertiesEquals(ImportFileLog expected, ImportFileLog actual) {
        assertImportFileLogUpdatableFieldsEquals(expected, actual);
        assertImportFileLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileLogAutoGeneratedPropertiesEquals(ImportFileLog expected, ImportFileLog actual) {
        assertThat(actual)
            .as("Verify ImportFileLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileLogUpdatableFieldsEquals(ImportFileLog expected, ImportFileLog actual) {
        assertThat(actual)
            .as("Verify ImportFileLog relevant properties")
            .satisfies(a -> assertThat(a.getLineIndex()).as("check lineIndex").isEqualTo(expected.getLineIndex()))
            .satisfies(a -> assertThat(a.getField()).as("check field").isEqualTo(expected.getField()))
            .satisfies(a -> assertThat(a.getErrorCode()).as("check errorCode").isEqualTo(expected.getErrorCode()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getRawLine()).as("check rawLine").isEqualTo(expected.getRawLine()))
            .satisfies(a -> assertThat(a.getSourceFamily()).as("check sourceFamily").isEqualTo(expected.getSourceFamily()))
            .satisfies(a -> assertThat(a.getNormalizedFamily()).as("check normalizedFamily").isEqualTo(expected.getNormalizedFamily()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileLogUpdatableRelationshipsEquals(ImportFileLog expected, ImportFileLog actual) {
        assertThat(actual)
            .as("Verify ImportFileLog relationships")
            .satisfies(a -> assertThat(a.getImportFile()).as("check importFile").isEqualTo(expected.getImportFile()));
    }
}
