package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportFileItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemAllPropertiesEquals(ImportFileItem expected, ImportFileItem actual) {
        assertImportFileItemAutoGeneratedPropertiesEquals(expected, actual);
        assertImportFileItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemAllUpdatablePropertiesEquals(ImportFileItem expected, ImportFileItem actual) {
        assertImportFileItemUpdatableFieldsEquals(expected, actual);
        assertImportFileItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemAutoGeneratedPropertiesEquals(ImportFileItem expected, ImportFileItem actual) {
        assertThat(actual)
            .as("Verify ImportFileItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemUpdatableFieldsEquals(ImportFileItem expected, ImportFileItem actual) {
        assertThat(actual)
            .as("Verify ImportFileItem relevant properties")
            .satisfies(a -> assertThat(a.getLineIndex()).as("check lineIndex").isEqualTo(expected.getLineIndex()))
            .satisfies(a -> assertThat(a.getRawData()).as("check rawData").isEqualTo(expected.getRawData()))
            .satisfies(a -> assertThat(a.getRawHash()).as("check rawHash").isEqualTo(expected.getRawHash()))
            .satisfies(a -> assertThat(a.getSourceFamily()).as("check sourceFamily").isEqualTo(expected.getSourceFamily()))
            .satisfies(a -> assertThat(a.getNormalizedFamily()).as("check normalizedFamily").isEqualTo(expected.getNormalizedFamily()))
            .satisfies(a -> assertThat(a.getNormalizedJson()).as("check normalizedJson").isEqualTo(expected.getNormalizedJson()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorCode()).as("check errorCode").isEqualTo(expected.getErrorCode()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportFileItemUpdatableRelationshipsEquals(ImportFileItem expected, ImportFileItem actual) {
        assertThat(actual)
            .as("Verify ImportFileItem relationships")
            .satisfies(a -> assertThat(a.getImportFile()).as("check importFile").isEqualTo(expected.getImportFile()))
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
