package com.asynctide.turnbridge.domain;

import static com.asynctide.turnbridge.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAllPropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertInvoiceItemAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAllUpdatablePropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertInvoiceItemUpdatableFieldsEquals(expected, actual);
        assertInvoiceItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAutoGeneratedPropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemUpdatableFieldsEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getSequence()).as("check sequence").isEqualTo(expected.getSequence()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemUpdatableRelationshipsEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem relationships")
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
