package com.asynctide.turnbridge.domain;

import static com.asynctide.turnbridge.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAllPropertiesEquals(Invoice expected, Invoice actual) {
        assertInvoiceAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAllUpdatablePropertiesEquals(Invoice expected, Invoice actual) {
        assertInvoiceUpdatableFieldsEquals(expected, actual);
        assertInvoiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAutoGeneratedPropertiesEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceUpdatableFieldsEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice relevant properties")
            .satisfies(a -> assertThat(a.getInvoiceNo()).as("check invoiceNo").isEqualTo(expected.getInvoiceNo()))
            .satisfies(a -> assertThat(a.getMessageFamily()).as("check messageFamily").isEqualTo(expected.getMessageFamily()))
            .satisfies(a -> assertThat(a.getBuyerId()).as("check buyerId").isEqualTo(expected.getBuyerId()))
            .satisfies(a -> assertThat(a.getBuyerName()).as("check buyerName").isEqualTo(expected.getBuyerName()))
            .satisfies(a -> assertThat(a.getSellerId()).as("check sellerId").isEqualTo(expected.getSellerId()))
            .satisfies(a -> assertThat(a.getSellerName()).as("check sellerName").isEqualTo(expected.getSellerName()))
            .satisfies(a ->
                assertThat(a.getSalesAmount())
                    .as("check salesAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSalesAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getTaxType()).as("check taxType").isEqualTo(expected.getTaxType()))
            .satisfies(a -> assertThat(a.getNormalizedJson()).as("check normalizedJson").isEqualTo(expected.getNormalizedJson()))
            .satisfies(a -> assertThat(a.getOriginalPayload()).as("check originalPayload").isEqualTo(expected.getOriginalPayload()))
            .satisfies(a -> assertThat(a.getInvoiceStatus()).as("check invoiceStatus").isEqualTo(expected.getInvoiceStatus()))
            .satisfies(a -> assertThat(a.getIssuedAt()).as("check issuedAt").isEqualTo(expected.getIssuedAt()))
            .satisfies(a -> assertThat(a.getLegacyType()).as("check legacyType").isEqualTo(expected.getLegacyType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceUpdatableRelationshipsEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice relationships")
            .satisfies(a -> assertThat(a.getImportFile()).as("check importFile").isEqualTo(expected.getImportFile()))
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
