package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceAssignNoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAssignNoAllPropertiesEquals(InvoiceAssignNo expected, InvoiceAssignNo actual) {
        assertInvoiceAssignNoAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceAssignNoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAssignNoAllUpdatablePropertiesEquals(InvoiceAssignNo expected, InvoiceAssignNo actual) {
        assertInvoiceAssignNoUpdatableFieldsEquals(expected, actual);
        assertInvoiceAssignNoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAssignNoAutoGeneratedPropertiesEquals(InvoiceAssignNo expected, InvoiceAssignNo actual) {
        assertThat(actual)
            .as("Verify InvoiceAssignNo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAssignNoUpdatableFieldsEquals(InvoiceAssignNo expected, InvoiceAssignNo actual) {
        assertThat(actual)
            .as("Verify InvoiceAssignNo relevant properties")
            .satisfies(a -> assertThat(a.getTrack()).as("check track").isEqualTo(expected.getTrack()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()))
            .satisfies(a -> assertThat(a.getFromNo()).as("check fromNo").isEqualTo(expected.getFromNo()))
            .satisfies(a -> assertThat(a.getToNo()).as("check toNo").isEqualTo(expected.getToNo()))
            .satisfies(a -> assertThat(a.getUsedCount()).as("check usedCount").isEqualTo(expected.getUsedCount()))
            .satisfies(a -> assertThat(a.getRollSize()).as("check rollSize").isEqualTo(expected.getRollSize()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAssignNoUpdatableRelationshipsEquals(InvoiceAssignNo expected, InvoiceAssignNo actual) {
        assertThat(actual)
            .as("Verify InvoiceAssignNo relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
