package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ManualActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualActionAllPropertiesEquals(ManualAction expected, ManualAction actual) {
        assertManualActionAutoGeneratedPropertiesEquals(expected, actual);
        assertManualActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualActionAllUpdatablePropertiesEquals(ManualAction expected, ManualAction actual) {
        assertManualActionUpdatableFieldsEquals(expected, actual);
        assertManualActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualActionAutoGeneratedPropertiesEquals(ManualAction expected, ManualAction actual) {
        assertThat(actual)
            .as("Verify ManualAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualActionUpdatableFieldsEquals(ManualAction expected, ManualAction actual) {
        assertThat(actual)
            .as("Verify ManualAction relevant properties")
            .satisfies(a -> assertThat(a.getActionType()).as("check actionType").isEqualTo(expected.getActionType()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()))
            .satisfies(a -> assertThat(a.getApprovedAt()).as("check approvedAt").isEqualTo(expected.getApprovedAt()))
            .satisfies(a -> assertThat(a.getResultMessage()).as("check resultMessage").isEqualTo(expected.getResultMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualActionUpdatableRelationshipsEquals(ManualAction expected, ManualAction actual) {
        assertThat(actual)
            .as("Verify ManualAction relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()))
            .satisfies(a -> assertThat(a.getImportFile()).as("check importFile").isEqualTo(expected.getImportFile()));
    }
}
