package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StoredObjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoredObjectAllPropertiesEquals(StoredObject expected, StoredObject actual) {
        assertStoredObjectAutoGeneratedPropertiesEquals(expected, actual);
        assertStoredObjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoredObjectAllUpdatablePropertiesEquals(StoredObject expected, StoredObject actual) {
        assertStoredObjectUpdatableFieldsEquals(expected, actual);
        assertStoredObjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoredObjectAutoGeneratedPropertiesEquals(StoredObject expected, StoredObject actual) {
        assertThat(actual)
            .as("Verify StoredObject auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoredObjectUpdatableFieldsEquals(StoredObject expected, StoredObject actual) {
        assertThat(actual)
            .as("Verify StoredObject relevant properties")
            .satisfies(a -> assertThat(a.getBucket()).as("check bucket").isEqualTo(expected.getBucket()))
            .satisfies(a -> assertThat(a.getObjectKey()).as("check objectKey").isEqualTo(expected.getObjectKey()))
            .satisfies(a -> assertThat(a.getMediaType()).as("check mediaType").isEqualTo(expected.getMediaType()))
            .satisfies(a -> assertThat(a.getContentLength()).as("check contentLength").isEqualTo(expected.getContentLength()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.getPurpose()).as("check purpose").isEqualTo(expected.getPurpose()))
            .satisfies(a -> assertThat(a.getFilename()).as("check filename").isEqualTo(expected.getFilename()))
            .satisfies(a -> assertThat(a.getStorageClass()).as("check storageClass").isEqualTo(expected.getStorageClass()))
            .satisfies(a -> assertThat(a.getEncryption()).as("check encryption").isEqualTo(expected.getEncryption()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoredObjectUpdatableRelationshipsEquals(StoredObject expected, StoredObject actual) {
        // empty method
    }
}
