package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrackRangeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackRangeAllPropertiesEquals(TrackRange expected, TrackRange actual) {
        assertTrackRangeAutoGeneratedPropertiesEquals(expected, actual);
        assertTrackRangeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackRangeAllUpdatablePropertiesEquals(TrackRange expected, TrackRange actual) {
        assertTrackRangeUpdatableFieldsEquals(expected, actual);
        assertTrackRangeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackRangeAutoGeneratedPropertiesEquals(TrackRange expected, TrackRange actual) {
        assertThat(actual)
            .as("Verify TrackRange auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackRangeUpdatableFieldsEquals(TrackRange expected, TrackRange actual) {
        assertThat(actual)
            .as("Verify TrackRange relevant properties")
            .satisfies(a -> assertThat(a.getSellerId()).as("check sellerId").isEqualTo(expected.getSellerId()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()))
            .satisfies(a -> assertThat(a.getPrefix()).as("check prefix").isEqualTo(expected.getPrefix()))
            .satisfies(a -> assertThat(a.getStartNo()).as("check startNo").isEqualTo(expected.getStartNo()))
            .satisfies(a -> assertThat(a.getEndNo()).as("check endNo").isEqualTo(expected.getEndNo()))
            .satisfies(a -> assertThat(a.getCurrentNo()).as("check currentNo").isEqualTo(expected.getCurrentNo()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getLockOwner()).as("check lockOwner").isEqualTo(expected.getLockOwner()))
            .satisfies(a -> assertThat(a.getLockAt()).as("check lockAt").isEqualTo(expected.getLockAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackRangeUpdatableRelationshipsEquals(TrackRange expected, TrackRange actual) {
        // empty method
    }
}
