package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurnkeyMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnkeyMessageAllPropertiesEquals(TurnkeyMessage expected, TurnkeyMessage actual) {
        assertTurnkeyMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertTurnkeyMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnkeyMessageAllUpdatablePropertiesEquals(TurnkeyMessage expected, TurnkeyMessage actual) {
        assertTurnkeyMessageUpdatableFieldsEquals(expected, actual);
        assertTurnkeyMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnkeyMessageAutoGeneratedPropertiesEquals(TurnkeyMessage expected, TurnkeyMessage actual) {
        assertThat(actual)
            .as("Verify TurnkeyMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnkeyMessageUpdatableFieldsEquals(TurnkeyMessage expected, TurnkeyMessage actual) {
        assertThat(actual)
            .as("Verify TurnkeyMessage relevant properties")
            .satisfies(a -> assertThat(a.getMessageId()).as("check messageId").isEqualTo(expected.getMessageId()))
            .satisfies(a -> assertThat(a.getMessageFamily()).as("check messageFamily").isEqualTo(expected.getMessageFamily()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getPayloadPath()).as("check payloadPath").isEqualTo(expected.getPayloadPath()))
            .satisfies(a -> assertThat(a.getReceivedAt()).as("check receivedAt").isEqualTo(expected.getReceivedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnkeyMessageUpdatableRelationshipsEquals(TurnkeyMessage expected, TurnkeyMessage actual) {
        assertThat(actual)
            .as("Verify TurnkeyMessage relationships")
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
