package com.asynctide.turnbridge.domain;

import static com.asynctide.turnbridge.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class UploadJobItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobItemAllPropertiesEquals(UploadJobItem expected, UploadJobItem actual) {
        assertUploadJobItemAutoGeneratedPropertiesEquals(expected, actual);
        assertUploadJobItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobItemAllUpdatablePropertiesEquals(UploadJobItem expected, UploadJobItem actual) {
        assertUploadJobItemUpdatableFieldsEquals(expected, actual);
        assertUploadJobItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobItemAutoGeneratedPropertiesEquals(UploadJobItem expected, UploadJobItem actual) {
        assertThat(actual)
            .as("Verify UploadJobItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobItemUpdatableFieldsEquals(UploadJobItem expected, UploadJobItem actual) {
        assertThat(actual)
            .as("Verify UploadJobItem relevant properties")
            .satisfies(a -> assertThat(a.getLineNo()).as("check lineNo").isEqualTo(expected.getLineNo()))
            .satisfies(a -> assertThat(a.getTraceId()).as("check traceId").isEqualTo(expected.getTraceId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getResultCode()).as("check resultCode").isEqualTo(expected.getResultCode()))
            .satisfies(a -> assertThat(a.getResultMsg()).as("check resultMsg").isEqualTo(expected.getResultMsg()))
            .satisfies(a -> assertThat(a.getBuyerId()).as("check buyerId").isEqualTo(expected.getBuyerId()))
            .satisfies(a -> assertThat(a.getBuyerName()).as("check buyerName").isEqualTo(expected.getBuyerName()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getAmountExcl())
                    .as("check amountExcl")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountExcl())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getAmountIncl())
                    .as("check amountIncl")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountIncl())
            )
            .satisfies(a -> assertThat(a.getTaxType()).as("check taxType").isEqualTo(expected.getTaxType()))
            .satisfies(a -> assertThat(a.getInvoiceDate()).as("check invoiceDate").isEqualTo(expected.getInvoiceDate()))
            .satisfies(a -> assertThat(a.getInvoiceNo()).as("check invoiceNo").isEqualTo(expected.getInvoiceNo()))
            .satisfies(a -> assertThat(a.getAssignedPrefix()).as("check assignedPrefix").isEqualTo(expected.getAssignedPrefix()))
            .satisfies(a -> assertThat(a.getRawPayload()).as("check rawPayload").isEqualTo(expected.getRawPayload()))
            .satisfies(a -> assertThat(a.getRawHash()).as("check rawHash").isEqualTo(expected.getRawHash()))
            .satisfies(a -> assertThat(a.getProfileDetected()).as("check profileDetected").isEqualTo(expected.getProfileDetected()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobItemUpdatableRelationshipsEquals(UploadJobItem expected, UploadJobItem actual) {
        assertThat(actual)
            .as("Verify UploadJobItem relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
