package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UploadJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobAllPropertiesEquals(UploadJob expected, UploadJob actual) {
        assertUploadJobAutoGeneratedPropertiesEquals(expected, actual);
        assertUploadJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobAllUpdatablePropertiesEquals(UploadJob expected, UploadJob actual) {
        assertUploadJobUpdatableFieldsEquals(expected, actual);
        assertUploadJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobAutoGeneratedPropertiesEquals(UploadJob expected, UploadJob actual) {
        assertThat(actual)
            .as("Verify UploadJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobUpdatableFieldsEquals(UploadJob expected, UploadJob actual) {
        assertThat(actual)
            .as("Verify UploadJob relevant properties")
            .satisfies(a -> assertThat(a.getJobId()).as("check jobId").isEqualTo(expected.getJobId()))
            .satisfies(a -> assertThat(a.getSellerId()).as("check sellerId").isEqualTo(expected.getSellerId()))
            .satisfies(a -> assertThat(a.getSellerName()).as("check sellerName").isEqualTo(expected.getSellerName()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()))
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getSourceFilename()).as("check sourceFilename").isEqualTo(expected.getSourceFilename()))
            .satisfies(a -> assertThat(a.getSourceMediaType()).as("check sourceMediaType").isEqualTo(expected.getSourceMediaType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getAccepted()).as("check accepted").isEqualTo(expected.getAccepted()))
            .satisfies(a -> assertThat(a.getFailed()).as("check failed").isEqualTo(expected.getFailed()))
            .satisfies(a -> assertThat(a.getSent()).as("check sent").isEqualTo(expected.getSent()))
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUploadJobUpdatableRelationshipsEquals(UploadJob expected, UploadJob actual) {
        assertThat(actual)
            .as("Verify UploadJob relationships")
            .satisfies(a -> assertThat(a.getOriginalFile()).as("check originalFile").isEqualTo(expected.getOriginalFile()))
            .satisfies(a -> assertThat(a.getResultFile()).as("check resultFile").isEqualTo(expected.getResultFile()));
    }
}
