package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookEndpointAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookEndpointAllPropertiesEquals(WebhookEndpoint expected, WebhookEndpoint actual) {
        assertWebhookEndpointAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookEndpointAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookEndpointAllUpdatablePropertiesEquals(WebhookEndpoint expected, WebhookEndpoint actual) {
        assertWebhookEndpointUpdatableFieldsEquals(expected, actual);
        assertWebhookEndpointUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookEndpointAutoGeneratedPropertiesEquals(WebhookEndpoint expected, WebhookEndpoint actual) {
        assertThat(actual)
            .as("Verify WebhookEndpoint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookEndpointUpdatableFieldsEquals(WebhookEndpoint expected, WebhookEndpoint actual) {
        assertThat(actual)
            .as("Verify WebhookEndpoint relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTargetUrl()).as("check targetUrl").isEqualTo(expected.getTargetUrl()))
            .satisfies(a -> assertThat(a.getSecret()).as("check secret").isEqualTo(expected.getSecret()))
            .satisfies(a -> assertThat(a.getEvents()).as("check events").isEqualTo(expected.getEvents()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookEndpointUpdatableRelationshipsEquals(WebhookEndpoint expected, WebhookEndpoint actual) {
        assertThat(actual)
            .as("Verify WebhookEndpoint relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
