package com.asynctide.turnbridge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookDeliveryLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryLogAllPropertiesEquals(WebhookDeliveryLog expected, WebhookDeliveryLog actual) {
        assertWebhookDeliveryLogAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookDeliveryLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryLogAllUpdatablePropertiesEquals(WebhookDeliveryLog expected, WebhookDeliveryLog actual) {
        assertWebhookDeliveryLogUpdatableFieldsEquals(expected, actual);
        assertWebhookDeliveryLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryLogAutoGeneratedPropertiesEquals(WebhookDeliveryLog expected, WebhookDeliveryLog actual) {
        assertThat(actual)
            .as("Verify WebhookDeliveryLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryLogUpdatableFieldsEquals(WebhookDeliveryLog expected, WebhookDeliveryLog actual) {
        assertThat(actual)
            .as("Verify WebhookDeliveryLog relevant properties")
            .satisfies(a -> assertThat(a.getDeliveryId()).as("check deliveryId").isEqualTo(expected.getDeliveryId()))
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getHttpStatus()).as("check httpStatus").isEqualTo(expected.getHttpStatus()))
            .satisfies(a -> assertThat(a.getAttempts()).as("check attempts").isEqualTo(expected.getAttempts()))
            .satisfies(a -> assertThat(a.getLastError()).as("check lastError").isEqualTo(expected.getLastError()))
            .satisfies(a -> assertThat(a.getDeliveredAt()).as("check deliveredAt").isEqualTo(expected.getDeliveredAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryLogUpdatableRelationshipsEquals(WebhookDeliveryLog expected, WebhookDeliveryLog actual) {
        assertThat(actual)
            .as("Verify WebhookDeliveryLog relationships")
            .satisfies(a -> assertThat(a.getWebhookEndpoint()).as("check webhookEndpoint").isEqualTo(expected.getWebhookEndpoint()));
    }
}
